### ISSUE TITLE
35 moves winning strategy failed

### ISSUE THREAD

**Issue by sksundep** [MaximRud/rv2#1]
Sir, 
The ai u have build which defeat anyone in 35 moves. I know one way to defeat your ai. I win here. And please reply me I want to give you more suggestions.
Thankyou
![Screenshot_2020-05-27-18-07-14-380_com android chrome](https://user-images.githubusercontent.com/55572203/83103429-4e932b00-a0d4-11ea-9446-61ef94e7cd06.jpg)

**Comment by fucusy** [comment]
@sksundep Would you like to try this one, http://www.bytedance.ai/gomoku.html? No one has beaten this AI.

**Comment by maximrud** [comment]
Hello. 

Not yet. In your example white has six  stones in line. Standard Gomoku requires a row of exactly five stones for a win: rows of six or more, called overlines, do not count. Unlike Free style Gomoku. See https://en.wikipedia.org/wiki/Gomoku. So white loses after two moves.

Maxim

От: Qiang Chen
Отправлено: 30 октября 2020 г. в 5:04
Кому: MaximRud/rv2
Копия: Subscribed
Тема: Re: [MaximRud/rv2] 35 moves winning strategy failed (#1)

@sksundep Would you like to try this one, http://www.bytedance.ai/gomoku.html? No one has beaten this AI.

**Comment by maximrud** [comment]
Standard Gomoku requires a row of exactly five stones for a win: rows of six or more, called overlines,
